### ISSUE TITLE
Rmd handling of :emoji: 

### ISSUE THREAD

**Issue by romainfrancois** [romainfrancois/emojirx#4]
So that in an Rmd document, we could type e.g. `:grinning_face:` and it would be rendered as 😀 in the knitted document.  

Not sure this can be handled by some `knitr` option. @yihui ? 

Is there a way to register some hook that would replace the regex `"[:]([a-zA-Z_]+)[:]"` by something based on `\\1`

**Comment by yihui** [comment]
There is a `document` hook, e.g.

```r
knitr::knit_hooks$set(document = function(x) {
  # gsub(..., x)
})
```

The tricky part is you probably do not want to replace all instances unconditionally, e.g. what if you want to show `:grinning_face:` literally? Should you look for backticks around it or backslashes before it?

**Comment by romainfrancois** [comment]
moved to: https://github.com/hadley/emo/issues/11
